language: r

cache:
  - packages
  - directories:
    - $HOME/.m2

before_install:
  - if [ -n "$GITHUB_PAT" ]; then echo "GITHUB_PAT=\"$GITHUB_PAT\"" >> ~/.Renviron; else echo "GITHUB_PAT is not set"; fi

branches:
  except:
    - appveyor

services:
  - mysql

before_script:
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS dbi_test; CREATE USER 'dbi_test'@'localhost' IDENTIFIED BY 'dbi_test'; GRANT ALL PRIVILEGES ON dbi_test.* TO 'dbi_test'@'localhost';"
  